default_install_hook_types: [commit-msg]
repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.21.0
    hooks:
      - id: commitlint
        additional_dependencies: ['@commitlint/config-conventional']
        stages: [commit-msg]